### ISSUE TITLE
flatpak-module local-build not working in toolbox

### ISSUE THREAD

**Issue by Zlopez** [containers/toolbox#323]
I'm using toolbox on Fedora 31 Silverblue and if I try to build flatpak I'm working on using `flatpak-module local-build` I'm getting the following:
```
flatpak-module local-build --install                                                                                                                                                            Tue Nov  5 14:05:54 2019
2019-11-05 14:06:02,802 - MainThread - moksha.hub - WARNING - Cannot find qpid python module. Make sure you have python-qpid installed.
2019-11-05 14:06:03,028 - MainThread - MBS.utils.greenwave - WARNING - Greenwave is not configured or configured improperly
Failed to set locale, defaulting to C.UTF-8
BUILDING MODULE
===============
warning: Greenwave is not configured or configured improperly
Traceback (most recent call last):
  File "/usr/bin/mbs-manager", line 11, in <module>
    load_entry_point('module-build-service==2.29.1', 'console_scripts', 'mbs-manager')()
  File "/usr/lib/python3.7/site-packages/module_build_service/manage.py", line 265, in manager_wrapper
    manager.run()
  File "/usr/lib/python3.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/lib/python3.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/lib/python3.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/module_build_service/manage.py", line 172, in build_module_locally
    stream=str(stream), skiptests=skiptests
  File "/usr/lib/python3.7/site-packages/module_build_service/utils/submit.py", line 541, in submit_module_build_from_yaml
    return submit_module_build(db_session, username, mmd, params)
  File "/usr/lib/python3.7/site-packages/module_build_service/utils/submit.py", line 914, in submit_module_build
    mmds = generate_expanded_mmds(db_session, mmd, raise_if_stream_ambigous, default_streams)
  File "/usr/lib/python3.7/site-packages/module_build_service/utils/mse.py", line 388, in generate_expanded_mmds
    db_session, current_mmd, default_streams, raise_if_stream_ambigous)
  File "/usr/lib/python3.7/site-packages/module_build_service/utils/mse.py", line 336, in get_mmds_required_by_module_recursively
    all_base_module_mmds)
  File "/usr/lib/python3.7/site-packages/module_build_service/utils/mse.py", line 170, in _get_mmds_from_requires
    mmds[ns] += resolver.get_buildrequired_modulemds(name, stream, base_module_mmd)
  File "/usr/lib/python3.7/site-packages/module_build_service/resolver/MBSResolver.py", line 255, in get_buildrequired_modulemds
    modules = self._get_modules(name, stream, strict=False, base_module_br=base_module_nsvc)
  File "/usr/lib/python3.7/site-packages/module_build_service/resolver/MBSResolver.py", line 76, in _get_modules
    raise RuntimeError(self._generic_error % (query, res.status_code))
RuntimeError: Failed to query MBS with query {'name': 'flatpak-runtime', 'stream': 'f30', 'state': ['ready'], 'verbose': True, 'order_desc_by': 'version', 'page': 1, 'per_page': 10, 'base_module_br': <Modulemd.ModuleStreamV2 object at 0x7f50293df4b0 (ModulemdModuleStreamV2 at 0x55cb4ae00ad0)>} returned HTTP status 400

error: mbs-manager build_module_locally failed
error: log: None
```

I have Fedora 30 VM where this is working without issue, but I would rather use toolbox for this work.

**Comment by HarryMichal** [comment]
Hi @Zlopez, I already encountered this problem. It's caused by a faulty `module-build-service` package (https://bodhi.fedoraproject.org/updates/?packages=module-build-service). It's the current stable release. But just a few minutes ago a new release was added to the testing repo, so you can give it a try and if you have a fedora account, you can give it a positive or negative karma.

If it doesn't then downgrading to the previous version (2.28.2) should solve the problem temporarily.

**Comment by Zlopez** [comment]
Thanks for the info about update, but the issue is still there. I will probably wait for fix and work on something else in the meantime.

**Comment by Zlopez** [comment]
Solved by https://bodhi.fedoraproject.org/updates/FEDORA-2019-6ac0548dee
